services:
  db:
    image: mysql:8
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
      MYSQL_ROOT_PASSWORD: nest
      MYSQL_DATABASE: nest
      
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
volumes:
  mysql_data: